### PR TITLE
UHM-4102:  Don't show No order on Labs page until search is complete

### PR DESCRIPTION
**Pull request by ingpablo509**
@mogoodrich @cioan  can you review this modification please ?

### CODE REVIEW

**Comment by cioan** [comment]
Thanks @ingpablo509 . This looks good, i think the only change you made is this?
https://github.com/openmrs/openmrs-owa-labworkflow/pull/159/files#diff-e6b27419dac52d81e809c5b5a4075a3bR392
For some reason, it looks like every single line was changed, but maybe this is because your system  has automatically changed the format of the file? 
Can you please update the PR to only show the lines you changed? Thanks. This article might be helpful on how to configure line endings on your system:
https://help.github.com/en/articles/configuring-git-to-handle-line-endings

**Comment by ingpablo509** [comment]
> Thanks @ingpablo509 . This looks good, i think the only change you made is this?
> https://github.com/openmrs/openmrs-owa-labworkflow/pull/159/files#diff-e6b27419dac52d81e809c5b5a4075a3bR392
> For some reason, it looks like every single line was changed, but maybe this is because your system has automatically changed the format of the file?
> Can you please update the PR to only show the lines you changed? Thanks. This article might be helpful on how to configure line endings on your system:
> https://help.github.com/en/articles/configuring-git-to-handle-line-endings

ok thanks @cioan  i'll do it

**Comment by cioan** [comment]
Thanks @ingpablo509 for the new commit today. Can I ignore yesterday commit? The only change you made to this file is commenting out Line 392:     //fetched: state.labOrders.orders 
?

**Comment by ingpablo509** [comment]
> Thanks @ingpablo509 for the new commit today. Can I ignore yesterday commit? The only change you made to this file is commenting out Line 392: //fetched: state.labOrders.orders
> ?

yes @cioan

**Comment by ingpablo509** [comment]
> Thanks @ingpablo509 for the new commit today. Can I ignore yesterday commit? The only change you made to this file is commenting out Line 392: //fetched: state.labOrders.orders
> ?
I commented on the Line (392: //fetched: state.labOrders.orders), and the resolution is on the Line (393: fetched: state.labOrders.fetched).

**Pull request closed without merging**
